# Site settings
title: Ember Mist
email: booking@embermist.band
description: "Welcome to the webpage of the band Ember Mist."
baseurl: "https://embermist.band"
url: "https://embermist.band"

instagram_username: ember_mist_band

# Build settings
markdown: kramdown
