title: Ember Mist
tagline: A Seattle based original rock band
email: booking@embermist.band
description: >-
  The website for Ember Mist a seattle based rock band.
url: "https://embermist.band"
author: Ragav Venkatesan
instagram:
  username: ember_mist_band
  card: summary
soundcloud:
  username: ember-mist
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
# Build settings
markdown: kramdown
remote_theme: ItsPatrq/minimal-categorized
pagination:
  enabled: true
  per_page: 4
  limit: 0
  sort_field: 'date'
  sort_reverse: true

  exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - node_modules

collections:
  home:
    output: true
    permalink: /:path/

permalink: /:title.html
